### ISSUE TITLE
Use response status code instead of body content

### ISSUE THREAD

**Issue by pzmi-f3** [form3tech-oss/github-team-approver#33]
To determine whether configuration file exists `github-team-approver` uses body contents. In the newer revisions of `go-github` there's a response with a status code returned by GitHub. We can use this status code instead of relying on the error message from the body.

https://github.com/form3tech-oss/github-team-approver/blob/master/internal/api/github/client.go#L53

Background:
https://github.com/form3tech-oss/github-team-approver/pull/32#discussion_r818459905

**Comment by przechrzta-f3** [comment]
Implemented in [ticket](https://github.com/form3tech/platform-containers-release-team/issues/35)
